feat(BUGS-2826): recovery tool
LykkeBusiness/MarginTrading.AccountsManagement pull request #169
Opened 2022-11-08 14:14 UTC by gponomarev-lykke

2022-11-08 14:41 UTC, tarurar submitted a review, later dismissed

2022-11-08 14:41 UTC, tarurar commented on MarginTrading.AccountsManagement.RecoveryTool/LogParsers/AccountsManagementLogParser.cs
> +        var margin = Create("UpdateBalanceCommandsHandler:");
why is it "margin"?

2022-11-08 14:41 UTC, tarurar commented on MarginTrading.AccountsManagement.RecoveryTool/LogParsers/AccountsManagementLogParser.cs
> +        var margin = Create("UpdateBalanceCommandsHandler:");
just curious.

2022-11-09 06:23 UTC, gponomarev-lykke commented on MarginTrading.AccountsManagement.RecoveryTool/LogParsers/AccountsManagementLogParser.cs
> +        var margin = Create("UpdateBalanceCommandsHandler:");
Oh, I think it's just copy-paste from the activities recovery tool. Will fix

2022-11-09 07:37 UTC, tarurar requested changes

2022-11-09 07:37 UTC, tarurar commented on MarginTrading.AccountsManagement.RecoveryTool/Services/Publisher.cs
> +        var factory = new ConnectionFactory {Uri = new Uri(rabbitMqConnectionString, UriKind.Absolute)};
Let's use AutomaticRecoveryEnabled and set NetworkRecoveryInterval to, let's say 60 seconds.

2022-11-09 07:37 UTC, tarurar commented on MarginTrading.AccountsManagement.RecoveryTool/Services/Publisher.cs
> +        _publishingChannel.BasicPublish("",
Let's use mandatory option and handle messages which were not delivered.

2022-11-09 07:37 UTC, tarurar commented on MarginTrading.AccountsManagement.RecoveryTool/appsettings.json
> +    "db": "Server=13.69.102.164,1433;Initial Catalog=nova;Persist Security Info=False;User ID=novasql;Password=QAzP6b8rwwzJb#hc;MultipleActiveResultSets=False;Encrypt=False;Connection Timeout=90;",
We can't publish sensitive data to git

2022-11-14 10:26 UTC, tarurar approved these changes

2022-11-14 10:28 UTC, merged