Lt 4257 loss percentage
LykkeBusiness/MarginTrading.AccountsManagement pull request #170
Opened 2022-11-10 16:18 UTC by lykke-vashetsin

2022-11-17 10:54 UTC, tarurar requested changes

2022-11-17 10:54 UTC, tarurar commented on src/MarginTrading.AccountsManagement/RabbitMq/TopicPublishingStrategy.cs
> +    public sealed class TopicPublishingStrategy : IRabbitMqPublishStrategy
We have this version of Rabbit library where TopicPublishingStrategy is already defined. Please reuse it.
https://github.com/LykkeBusinessPlatform/Lykke.RabbitMqDotNetBroker/releases/tag/9.3.3

2022-11-17 10:54 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/AzureStorage/AccountHistoryRepository.cs
> +    internal class AccountHistoryRepository : IAccountHistoryRepository
Do we need this class at all?

2022-11-17 10:54 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/AzureStorage/LossPercentageRepository.cs
> +namespace MarginTrading.AccountsManagement.Repositories.Implementation.AzureStorage
And this one

2022-11-17 10:54 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/AccountHistoryRepository.cs
> +        private const string CalculateLossPercentageQuery =
This looks ugly, can we move it to stored procedure?

2022-11-17 10:54 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/AccountHistoryRepository.cs
> +            return await conn.QuerySingleAsync<AccountHistoryLossPercentageEntity>(
Is it okay if we raise an exception here if there is no record returned from the SQL query?

2022-11-17 10:54 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/LossPercentageRepository.cs
> +            catch (Exception ex)
Do we really have to catch it here?

2022-11-17 10:54 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/LossPercentageRepository.cs
> +        public async Task<ILossPercentage> GetLastAsync()
Can you mark it with `[ItemCanBeNull`] attribute?

2022-11-17 10:54 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/LossPercentageRepository.cs
> +            var entity = _convertService.Convert<LossPercentageEntity>(value);
What if `entity == null` here?

2022-11-17 10:54 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Workflow/BrokerSettings/EodProcessFinishedListener.cs
> +            CalculateLossPercentageIfNeeded();
I think better to run this first and then subscribe. Otherwise you'll have to deal with threads synchronisation.

2022-11-17 10:54 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Workflow/BrokerSettings/EodProcessFinishedListener.cs
> +            if (!_settings.LossPercentageCalculationEnabled)
Maybe it would be better to subscribe optionally?

2022-11-17 10:54 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Workflow/BrokerSettings/EodProcessFinishedListener.cs
> +                var value = newLossPercentage.LooserNumber / newLossPercentage.ClientNumber;
Do you have a test for this? What if `newLossPercentage.ClientNumber = 0`?

2022-11-17 10:54 UTC, tarurar commented on tests/MarginTrading.AccountsManagement.Tests/EodProcessFinishedListenerTests.cs
> +            _systemClockMock.Verify(mock => mock.UtcNow, Times.Never());
Wouldn't it be better it use `_lossPercentageRepositoryMock` instead here?

2022-11-17 10:54 UTC, tarurar commented on tests/MarginTrading.AccountsManagement.Tests/EodProcessFinishedListenerTests.cs
> +            _lossPercentageRepositoryMock.Verify(x => x.AddAsync(
Isn't just this line enough for the test?

2022-11-17 10:54 UTC, tarurar commented on tests/MarginTrading.AccountsManagement.Tests/EodProcessFinishedListenerTests.cs
> +        public void CalculateLossPercentageIfNeeded_LastLossPercentageNotNullAndExpired_Calculates()
Do you check if calculation.ClientNumber == 0 after calculation? You are using it as a divider so it can cause an exceptional situation.

2022-11-17 11:25 UTC, lykke-vashetsin commented on src/MarginTrading.AccountsManagement/InternalModels/LossPercentage.cs
> +        public int Id { get; }
for now no need since it is mapped when fetching from db

2022-11-17 11:42 UTC, lykke-vashetsin commented on src/MarginTrading.AccountsManagement/RabbitMq/TopicPublishingStrategy.cs
> +    public sealed class TopicPublishingStrategy : IRabbitMqPublishStrategy
done

2022-11-17 11:43 UTC, lykke-vashetsin commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/AzureStorage/AccountHistoryRepository.cs
> +    internal class AccountHistoryRepository : IAccountHistoryRepository
deleted

2022-11-17 11:43 UTC, lykke-vashetsin commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/AzureStorage/LossPercentageRepository.cs
> +namespace MarginTrading.AccountsManagement.Repositories.Implementation.AzureStorage
deleted

2022-11-17 11:47 UTC, lykke-vashetsin commented on tests/MarginTrading.AccountsManagement.Tests/EodProcessFinishedListenerTests.cs
> +            _systemClockMock.Verify(mock => mock.UtcNow, Times.Never());
done

2022-11-17 11:48 UTC, lykke-vashetsin commented on tests/MarginTrading.AccountsManagement.Tests/EodProcessFinishedListenerTests.cs
> +            _lossPercentageRepositoryMock.Verify(x => x.AddAsync(
done

2022-11-17 12:01 UTC, lykke-vashetsin commented on tests/MarginTrading.AccountsManagement.Tests/EodProcessFinishedListenerTests.cs
> +        public void CalculateLossPercentageIfNeeded_LastLossPercentageNotNullAndExpired_Calculates()
done

2022-11-17 12:05 UTC, lykke-vashetsin commented on src/MarginTrading.AccountsManagement/Workflow/BrokerSettings/EodProcessFinishedListener.cs
> +            if (!_settings.LossPercentageCalculationEnabled)
done

2022-11-17 12:07 UTC, lykke-vashetsin commented on src/MarginTrading.AccountsManagement/RabbitMq/Publishers/LossPercentagePublisher.cs
> +                _log.LogWarning(e, "An error occurred while publishing event.", message.ToJson());
was consequent with other publishers in other services. shall I remove it? I was not able to find global error handling in account management

2022-11-18 08:46 UTC, lykke-vashetsin commented on src/MarginTrading.AccountsManagement/RabbitMq/Publishers/LossPercentagePublisher.cs
> +                _log.LogWarning(e, "An error occurred while publishing event.", message.ToJson());
just figured out there is already UseLykkeMiddleware there

2022-11-18 08:53 UTC, lykke-vashetsin commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/AccountHistoryRepository.cs
> +            return await conn.QuerySingleAsync<AccountHistoryLossPercentageEntity>(
that query should always return a single row hence I think it is expected to get an exception in other cases

2022-11-18 08:54 UTC, lykke-vashetsin commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/LossPercentageRepository.cs
> +            catch (Exception ex)
deleted, but was just consequent with other repositories in the same service

2022-11-18 09:07 UTC, lykke-vashetsin commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/LossPercentageRepository.cs
> +            var entity = _convertService.Convert<LossPercentageEntity>(value);
done

2022-11-18 10:17 UTC, lykke-vashetsin commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/AccountHistoryRepository.cs
> +        private const string CalculateLossPercentageQuery =
done

2022-11-18 10:53 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Scripts/dbo.CalculateLossPercentage.sql
> +-- exec sp_helptext [dbo.removeTaxFileMissing]
These are copy-pasted from another script file.

2022-11-18 10:53 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Startup/ApplicationConfiguration.cs
> +#if DEBUG
It looks like in this case `GlobalErrorHandlerMiddleware` will not be added.

2022-11-18 10:53 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Workflow/BrokerSettings/EodProcessFinishedListener.cs
> +            if (!_settings.LossPercentageCalculationEnabled)
I do not see you are subscribing optionally.

2022-11-18 11:15 UTC, lykke-vashetsin commented on src/MarginTrading.AccountsManagement/Scripts/dbo.CalculateLossPercentage.sql
> +-- exec sp_helptext [dbo.removeTaxFileMissing]
done

2022-11-18 11:35 UTC, tarurar approved these changes

2023-01-10 08:17 UTC, tarurar approved these changes

2023-01-10 12:02 UTC, tarurar approved these changes

2023-01-10 12:03 UTC, merged