[LT 4386] Update Account Data updating ClientProfile
LykkeBusiness/MarginTrading.AccountsManagement pull request #180
Opened 2023-01-17 13:21 UTC by fatihdumanli

[LT-4383](https://lykke-snow.atlassian.net/browse/LT-4383)

It turns out that the **ModificationTimeStamp** does not get updated after updating clients' **ClientProfile**.  This situation causes issues with cached account data.

This PR introduces changes to update clients' all accounts upon updating ClientProfile.

2023-01-17 15:26 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Services/Implementation/AccountManagementService.cs
> +                await _accountsRepository.UpdateAccountAsync(account.Id, isDisabled: false, isWithdrawalDisabled: false);
I think the only purpose of this call is to fire `AccountChangedEvent`. Am I right? 
If this is correct then `AccountChangedEvent` is already being triggered a bit later on 526. So what do we need this call for?

2023-01-17 15:34 UTC, fatihdumanli commented on src/MarginTrading.AccountsManagement/Services/Implementation/AccountManagementService.cs
> +                await _accountsRepository.UpdateAccountAsync(account.Id, isDisabled: false, isWithdrawalDisabled: false);
Not exactly. Even though the event is fired as you mentioned, the `ModificationTimestamp` column in the table remains the same, which is counterintuitive.

The purpose of this call is to update `ModificationTimestamp` column by calling AccountRepository.UpdateAccountAsync().

https://github.com/LykkeBusiness/MarginTrading.AccountsManagement/blob/master/src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/AccountsRepository.cs#L405

2023-01-17 15:48 UTC, tarurar requested changes

2023-01-17 15:49 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Services/Implementation/AccountManagementService.cs
> +                await _accountsRepository.UpdateAccountAsync(account.Id, isDisabled: false, isWithdrawalDisabled: false);
Also it would be nice to have unit test to cover this case.

2023-01-18 15:33 UTC, tarurar requested changes

2023-01-18 15:33 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/AccountsRepository.cs
> +                    c.LastUpdatedAt
```suggestion
                    c.LastUpdatedAt as ClientLastUpdatedAt

```

2023-01-18 15:33 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/AccountsRepository.cs
> +                    c.LastUpdatedAt
In order to not have confusion I think fields `ModificationTimestamp` and `LastUpdatedAt` should have the same name.

2023-01-18 15:33 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/AccountsRepository.cs
> +            DateTimeExtensions.OverwriteTimestampWithMostRecent<AccountEntity>(accounts,
This is a part of business logic , should not be implemented inside repository pattern. Use either domain model behaviour or service class behaviour in case of anemic domain model (our case). However, I don't like this approach at all. You fetch the AccountEntity and then have to call `DateTimeExtensions.OverwriteTimestampWithMostRecent` to have AccountEntity consistent. What if another developer will only fetch AccountEntity but not call `DateTimeExtensions.OverwriteTimestampWithMostRecent` afterwards? He or she will get inconsistent data.
We need a consistent and reliable way to get AccountEntity without additional second-step modifications.

2023-01-18 15:33 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/AccountEntity.cs
> +        public DateTime LastUpdatedAt { get; set; }
Now it confuses me, why do we need `LastUpdatedAt` property on Account level? Now you have two properties: `ModificationTimestamp` and `LastUpdatedAt`. In a month it will be hard even for you to understand that code and explain what these properties mean.

2023-01-18 15:33 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/AccountsRepository.cs
> +            var rawSql = $"update {ClientsTableName} " +
How can you guarantee that every update of ClientsTableName will lead to `LastUpdatedAt` field update?

2023-01-18 16:07 UTC, fatihdumanli commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/AccountEntity.cs
> +        public DateTime LastUpdatedAt { get; set; }
We need such a property on the Account level because the join query gets the `LastUpdatedAt` value from Clients table, just like the `TradingConditionId` and `UserId`.

2023-01-18 17:09 UTC, tarurar commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/AccountEntity.cs
> +        public DateTime LastUpdatedAt { get; set; }
But it confuses. In this case I'd suggest using something like AccountRecord to mimic the SQL query/table structure. And then map it to AccountEntity.

2023-01-18 17:25 UTC, fatihdumanli commented on src/MarginTrading.AccountsManagement/Repositories/Implementation/SQL/AccountsRepository.cs
> +            DateTimeExtensions.OverwriteTimestampWithMostRecent<AccountEntity>(accounts,
Then I suppose that leaves us with two possible options.

1. While reading from the database, mapping **ModificationTimestamp** to another property in the **AccountEntity** class. Then move the logic to the getter of the **ModificationTimestamp**, basically an encapsulation. Something like below. That way the ModificationTimestamp will always be consistent no matter where it is read from.

```
//map column to this propery
internal DateTime _modificationTimeStamp;

//encapsulate the field.
 public DateTime ModificationTimestamp
        {
            get
            {
                return DateTimeExtensions.MaxDateTime(this._modificationTimeStamp, this.ClientLastUpdatedAt);
            }

            set 
            {
                _modificationTimeStamp = value;
            }
        }
```

2. Moving the logic to the database level using a SQL trigger, updating the **ModificationTimestamp** upon every change in Client table, however, I'm a little bit reluctant to go down that path.

2023-01-19 08:53 UTC, fatihdumanli commented
Closing this PR as the team agreed on different approach.

2023-01-19 08:53 UTC, closed without merging